[package]
name = "async-dnssd"
build = "build.rs"
version = "0.3.0"
authors = ["Stefan Bühler <stbuehler@web.de>"]
description = "Asynchronous wrapper for DNS-SD C libraries"
documentation = "https://stbuehler.github.io/rustdocs/async-dnssd/async_dnssd/"
homepage = "https://github.com/stbuehler/rust-async-dnssd"
repository = "https://github.com/stbuehler/rust-async-dnssd"
readme = "README.md"
keywords = ["dnssd", "dns-sd", "mdns", "network", "async"]
license = "MIT"

[build-dependencies]
pkg-config = "0.3.9"

[dependencies]
futures = "0.1.15"
mio = "0.6"
tokio-core = "0.1.8"
log = "0.3.8"

[target.'cfg(windows)'.dependencies]
libc = "0.2.24"
ws2_32-sys = "0.2.1"
winapi = "0.2.5"
